name: chemical-representation-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==23.1.2
  - pip-tools==6.13.0
  - setuptools==67.7.2
  - wheel==0.40.0
  - pytest==7.2.2
  - numpy==1.22.4
  - pandas==1.5.3
  - matplotlib==3.7.1
  - matplotlib-inline==0.1.6
  - matplotlib-venn==0.11.9
  - Markdown==3.4.3
  - markdown-it-py==2.2.0
  - networkx==3.1
  - nltk==3.8.1
  - notebook==6.4.8
  - tensorflow==2.12.0
  - text-unidecode==1.3
  - toml==0.10.2
  - torch==2.0.1+cu118
  - urllib3==1.26.15
  - seaborn==0.12.2
  - rdkit-pypi==2022.9.5
  - PyYAML==6.0
  - xgboost==1.7.5
  - glob2==0.7
  - ipython==7.34.0
  - jax==0.4.10
  - keras==2.12.0
  - drfp==0.3.6
  - xtb
  - zipp==3.15.0
  - sklearn-pandas==2.2.0
  - scikit-learn==1.2.2
  - scipy==1.10.1
  - morfeus-ml==0.7.2
  - mordred==1.2.0
  - torch-geometric
  - datamol==0.10.3
  - molfeat==0.8.9
  - transformers==4.30.0
  - xarray==2022.12.0